version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "043942809940"
    AWS_REGION: "ap-south-1"
    IMAGE_REPO_NAME: "springboot/frontend"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # 安装必要的依赖
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      # 构建前端项目
      - echo "Building the front-end project..."
      - npm run build

  build:
    commands:
      # 构建 Docker 镜像
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:latest .

      # 登录到 ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  post_build:
    commands:
      # 将镜像标记为 ECR 的最新版本
      - echo "Tagging the Docker image..."
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

      # 推送镜像到 ECR
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

artifacts:
  files:
    - '**/*'