version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "043942809940"
    AWS_REGION: "ap-northeast-2"
    IMAGE_REPO_NAME: "springboot/hello"

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
      - echo "Installing Docker..."
      - yum install -y docker
      - docker info

  pre_build:
    commands:
      - echo "Building the Maven project..."
      - docker run --rm -v $(pwd):/usr/src/mymaven -w /usr/src/mymaven maven:3.8.6-openjdk-17 mvn clean install

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:latest .
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Tagging the Docker image..."
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Updating ECS service with the new image..."
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment

artifacts:
  files:
    - '**/*'